### PR TITLE
Added ability to read in an MFA token.

### PR DESCRIPTION
**Pull request by andylockran**
*Issue #13 *

*Description of changes:*

I've parsed the first authentication response, and upon finding MFA_REQUIRED, sends another request with the passcode and sessionToken to return a one-time-code; this then continues the normal flow of the application.

_Limitations - this will always select the first MFA token_ . (as this resolves my use case).  Will add additional functionality for multiple MFA selection and create a new issue to do so.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by joshk0** [comment]
hi @andylockran , what is the difference between this and #14 ?

**Comment by andylockran** [comment]
Completely honest; I hadn’t seen #14 when I submitted it. I’ll test out 14 and get back to you. 
I’ve also reached out directly to okta, and had a positive response to create a higher level lib to import instead of a custom implementation.

**Comment by joshk0** [comment]
No problem. I'm just a potential user of either of these pull requests and want to know which one I should use. It sounds like you should peek over and see if the two are mutually compatible in approach, work with the author and create a unified PR. I am wondering if the folks at AWS Labs will express a strong direction for whether this sort of thing belongs in awsprocesscreds and support the change, I think this change going in would be enormously consequential for a lot of teams using Okta and looking to tie it to AWS.

**Comment by JordonPhillips** [comment]
Thanks for the pr! I think I would prefer to go down the route of #14, which adds support for some other things in addition to this. Does that PR address your use case?

I'm going to close this pr, but feel free to re-open if the other pr doesn't address your case.

**Pull request closed without merging**
